### ISSUE TITLE
Web Server not starting

### ISSUE THREAD

**Issue by tobyweston** [ericmann/speed-logger#7]
Starting up with `node speed.js` doesn't output anything in the console but I can infer it's running as the `log.csv` is generated. However, I can't get any site up using `http://host:3131` or `http://host:3131/index.html`. Any clues so I can tell if the http server is running or not?

Changing the config to show charts on the console doesn't help. I literally get no output to the console either way. Not even errors.

oh, hang on. I spotted I have to set `consoleLog: true`. I'm getting er, console logs now! 👍 

```
Start webserver on 0.0.0.0:3131 every 10 minutes refresh

 Running test ...
2018-12-08 12:52:58 => IP: 82.42.190.108 | Ping: 20.036ms | Download: 194.13 MB/s | Upload: 12.31 MB/s | Server: Clouvider Limited
```

but I still get nothing from `curl` or the browser...

**Comment by ericmann** [comment]
Try `http://localhost:3131` instead of `host:3131`. I just cloned this down on a brand new machine with a clean environ and everything runs and is visible in the browser just fine.
